<?php
require_once __DIR__ . '/../includes/functions.php'; admin_required();
$orderNo = clean_guest($_GET['id'] ?? ''); $message='';
try {
    $q=db()->prepare('SELECT o.*,c.name,c.whatsapp,c.email,oi.template_id,oi.template_name FROM orders o JOIN customers c ON c.id=o.customer_id JOIN order_items oi ON oi.order_id=o.id WHERE o.order_number=? LIMIT 1'); $q->execute([$orderNo]); $order=$q->fetch();
    if (!$order) { http_response_code(404); exit('Order tidak ditemukan.'); }
    if ($_SERVER['REQUEST_METHOD']==='POST') { verify_csrf(); $action=$_POST['action']??'';
        if ($action==='verify') { $pdo=db(); $pdo->beginTransaction(); $pdo->prepare('UPDATE payments SET status="verified",paid_at=NOW() WHERE order_id=?')->execute([$order['id']]); $pdo->prepare('UPDATE orders SET status="paid" WHERE id=?')->execute([$order['id']]); $slug=slugify($order['name'].'-'.$orderNo); $pdo->prepare('INSERT INTO invitations(order_id,template_id,slug,status) VALUES(?,?,?,"draft") ON DUPLICATE KEY UPDATE template_id=VALUES(template_id)')->execute([$order['id'],$order['template_id'],$slug]); $pdo->commit(); $message='Pembayaran terverifikasi dan invitation draft dibuat.';
        } elseif ($action==='activate') { $q=db()->prepare('UPDATE invitations SET status="active" WHERE order_id=?'); $q->execute([$order['id']]); db()->prepare('UPDATE orders SET status="active" WHERE id=?')->execute([$order['id']]); $message='Invitation diaktifkan.'; }
        $q->execute([$orderNo]); $order=$q->fetch();
    }
} catch(Throwable $exception) { if(isset($pdo)&&$pdo->inTransaction())$pdo->rollBack(); $message='Aksi gagal. Pastikan database sudah di-import dan template sudah disinkronkan.'; }
$invitation=null; try{$q=db()->prepare('SELECT * FROM invitations WHERE order_id=? LIMIT 1');$q->execute([$order['id']]);$invitation=$q->fetch();}catch(Throwable){}
$page_title='Order '.$orderNo; require __DIR__ . '/includes/header.php'; require __DIR__ . '/includes/sidebar.php';
?><header class="admin-header"><span class="eyebrow">ORDER DETAIL</span><h1><?= e($order['order_number']) ?></h1></header><?php if($message): ?><p class="notice"><?= e($message) ?></p><?php endif; ?><section class="form-card"><p><strong>Customer:</strong> <?= e($order['name']) ?></p><p><strong>WhatsApp:</strong> <?= e($order['whatsapp']) ?></p><p><strong>Template:</strong> <?= e($order['template_name']) ?></p><p><strong>Total:</strong> <?= e(money((int)$order['total'])) ?></p><p><strong>Status:</strong> <?= e($order['status']) ?></p><div class="actions"><?php if($order['status']==='pending_payment'||$order['status']==='waiting_confirmation'): ?><form method="post"><?= csrf_field() ?><input type="hidden" name="action" value="verify"><button class="button" type="submit">Verifikasi Pembayaran</button></form><?php endif; ?><?php if($invitation && $invitation['status']!=='active'): ?><form method="post"><?= csrf_field() ?><input type="hidden" name="action" value="activate"><button class="button" type="submit">Aktifkan Undangan</button></form><?php endif; ?><?php if($invitation): ?><a class="button secondary" href="/<?= e($invitation['slug']) ?>" target="_blank">Buka Undangan</a><a class="button secondary" href="/admin/invitation-edit.php?id=<?= e((string)$invitation['id']) ?>">Edit Data</a><?php endif; ?></div></section><?php require __DIR__ . '/includes/footer.php'; ?>
